name: inventario-finanzas-int
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - ruff
  - polars
  - fastexcel
  - xlrd
  - openpyxl
  - pyarrow
  - pip:
      - python-dotenv
      - mkdocs
      - -e .
